version: '2'

# expansions: 3

vars:
    PWD:
        sh: pwd
    TAG:
        sh: git describe --tags
    VERSION: "{{or .BUILD_VERSION .TAG}}"
    DATE: 
        sh: date +%FT%TZ%z
    BUILD_DIR: "{{ .PWD }}/build"
    
tasks:
    clean:
        cmds:
            - go clean
            - rm -rf "{{ .BUILD_DIR }}"
    test:
        cmds:
            - go test ./... -race -count=1
    lint:
        cmds:
            - golangci-lint run
    hkcam:
        cmds:
            - "go build -o {{ .BUILD_DIR }}/hkcam -ldflags {{ .LDFLAGS }} cmd/hkcam/main.go"
            - "{{ .BUILD_DIR }}/hkcam --verbose"
        vars:
            LDFLAGS: "\"-X main.Version={{ .VERSION }} -X main.Date={{ .DATE }}\""
        sources:
            - cmd/hkcam/main.go
            - ./*.go
            - Taskfile.yml
    hkcam-pack:
        cmds:
            - task: build-fs
            # Raspberry Pi
            - "GOOS=linux GOARCH=arm GOARM=6 go build -o {{ .BUILD_DIR }}/{{ .PACKAGE_RPI }}/{{ .BINARY }} -ldflags {{ .LDFLAGS }} cmd/hkcam/main.go cmd/hkcam/fs.go"
            # Linux
            - "GOOS=linux GOARCH=amd64 go build -o {{ .BUILD_DIR }}/{{ .PACKAGE_LINUX_64 }}/{{ .BINARY }} -ldflags {{ .LDFLAGS }} cmd/hkcam/main.go cmd/hkcam/fs.go"
            # Linux
            - "GOOS=linux GOARCH=386 go build -o {{ .BUILD_DIR }}/{{ .PACKAGE_LINUX_32 }}/{{ .BINARY }} -ldflags {{ .LDFLAGS }} cmd/hkcam/main.go cmd/hkcam/fs.go"
            # Intel Mac
            - "GOOS=darwin GOARCH=amd64 go build -o {{ .BUILD_DIR }}/{{ .PACKAGE_INTEL_MAC }}/{{ .BINARY }} -ldflags {{ .LDFLAGS }} cmd/hkcam/main.go cmd/hkcam/fs.go"
            # M1 Mac
            - "GOOS=darwin GOARCH=arm64 go build -o {{ .BUILD_DIR }}/{{ .PACKAGE_M1_MAC }}/{{ .BINARY }} -ldflags {{ .LDFLAGS }} cmd/hkcam/main.go cmd/hkcam/fs.go"
            # Copy Installation.md
            - "cp {{ .INSTALLATION }} {{ .BUILD_DIR }}/{{ .INSTALLATION }}"
            # pack
            - "tar -cvzf {{ .PACKAGE_RPI }}.tar.gz -C {{ .BUILD_DIR }} {{ .INSTALLATION }} -C {{ .BUILD_DIR }}/{{ .PACKAGE_RPI }} {{ .BINARY }}"
            - "tar -cvzf {{ .PACKAGE_LINUX_64 }}.tar.gz -C {{ .BUILD_DIR }} {{ .INSTALLATION }} -C {{ .BUILD_DIR }}/{{ .PACKAGE_LINUX_64 }} {{ .BINARY }}"
            - "tar -cvzf {{ .PACKAGE_LINUX_32 }}.tar.gz -C {{ .BUILD_DIR }} {{ .INSTALLATION }} -C {{ .BUILD_DIR }}/{{ .PACKAGE_LINUX_32 }} {{ .BINARY }}"
            - "tar -cvzf {{ .PACKAGE_INTEL_MAC }}.tar.gz -C {{ .BUILD_DIR }} {{ .INSTALLATION }} -C {{ .BUILD_DIR }}/{{ .PACKAGE_INTEL_MAC }} {{ .BINARY }}"
            - "tar -cvzf {{ .PACKAGE_M1_MAC }}.tar.gz -C {{ .BUILD_DIR }} {{ .INSTALLATION }} -C {{ .BUILD_DIR }}/{{ .PACKAGE_M1_MAC }} {{ .BINARY }}"
        vars:
            BINARY: hkcam
            PACKAGE_RPI: "{{ .BINARY }}-{{ .VERSION }}_linux_arm"
            PACKAGE_LINUX_64: "{{ .BINARY }}-{{ .VERSION }}_linux_amd64"
            PACKAGE_LINUX_32: "{{ .BINARY }}-{{ .VERSION }}_linux_386"
            PACKAGE_INTEL_MAC: "{{ .BINARY }}-{{ .VERSION }}_darwin_amd64"
            PACKAGE_M1_MAC: "{{ .BINARY }}-{{ .VERSION }}_darwin_arm64"
            LDFLAGS: "\"-X main.Version={{ .VERSION }} -X main.Date={{ .DATE }}\""